---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'A simple template intended to be run in S.Paulo (sa-east-1) with a Linux (1) distro.'
Resources:
  DB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass: db.t2.micro
      DBName: wordpress
      Engine: MySQL
      MasterUsername: wordpress
      MasterUserPassword: x529828Banco
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09e0d207dfce36486 # Linux (1), S.Paulo - Jul 2020
      InstanceType: t2.micro
  S3:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: wp-x529828sp # replace done before uploaded with random

